/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows95keygengui;

import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Matteo
 */
public class windows95KeygenGUI extends javax.swing.JFrame {

    /**
     * Creates new form windows95KeygenGUI
     */
    public windows95KeygenGUI() {
        initComponents();

        JFrame jframe = new JFrame("My JFrame Title");

        ImageIcon imageComputers = new ImageIcon("computers.png");

        labelPic.setText("");
        labelPic.setIcon(imageComputers);

        try {
            setIconImage(ImageIO.read(new File("icon.png")));
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelPic = new javax.swing.JLabel();
        lblCode = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Windows 95 Serial Generator");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Constantia", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Welcome to");

        labelPic.setBackground(new java.awt.Color(255, 255, 255));
        labelPic.setForeground(new java.awt.Color(0, 0, 0));
        labelPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPic.setText("[image]");

        lblCode.setEditable(false);
        lblCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblCode.setText("OEM Serial");
        lblCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Generate");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Windows");

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("95");

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("<html> Welcome to the Windows 95 OEM serial generator, click the button below to generate a valid key that can be used to activate any Windows 95 installation. </html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelPic, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblCode, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(labelPic, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        generateSerial();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(windows95KeygenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(windows95KeygenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(windows95KeygenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(windows95KeygenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new windows95KeygenGUI().setVisible(true);
            }
        });
    }
    
    public static void generateSerial(){
        
        Random rand = new Random();

        int intDay, intYear, intStageTwo, intSum = 0, intFinal;
        String strDayConverted = "", strStageTwoConverted = "", strStageThreeConverted = "";
        boolean blnDivBySeven;
        
        /*
        System.out.println("\t" + "Windows 95 OEM serial generator");
        System.out.println("-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-");
        System.out.println("\t" + "Press enter to generate a serial");
        System.out.println("");
        */

        
        
        intDay = rand.nextInt(366 - 1) + 1;

        if (intDay < 100) {

            strDayConverted = String.format("%03d", intDay);
            //System.out.print("\t \t" + strDayConverted);
        } else {
            //System.out.print("\t \t" + intDay);
        }

        intYear = rand.nextInt(2003 - 1995) + 1995;
        //System.out.print(String.valueOf(intYear).substring(2));
        //System.out.print("-OEM-");

        intStageTwo = rand.nextInt(999999 - 1) + 1;
        strStageTwoConverted = String.format("%07d", intStageTwo);

        while (intStageTwo != 0) {
            intSum = intSum + intStageTwo % 10;
            intStageTwo = intStageTwo / 10;
        }

        blnDivBySeven = intSum % 7 == 0;

        if (blnDivBySeven == false) {

            while (blnDivBySeven == false) {

                intStageTwo = rand.nextInt(999999 - 1) + 1;
                strStageTwoConverted = String.format("%07d", intStageTwo);
                intSum = 0;
                

                while (intStageTwo != 0) {
                    intSum = intSum + intStageTwo % 10;
                    intStageTwo = intStageTwo / 10;
                }
                
                blnDivBySeven = intSum % 7 == 0;
            }

            //System.out.print(strStageTwoConverted + "-");
            intFinal = rand.nextInt(99999 - 1) + 1;
            strStageThreeConverted = String.format("%05d", intFinal);
            //System.out.println(strStageThreeConverted);
            
            if (intDay < 100) {

            strDayConverted = String.format("%03d", intDay);
            lblCode.setText(strDayConverted + String.valueOf(intYear).substring(2) + "-OEM-" + strStageTwoConverted + "-" + strStageThreeConverted);
        } else {
            lblCode.setText(intDay + String.valueOf(intYear).substring(2) + "-OEM-" + strStageTwoConverted + "-" + strStageThreeConverted);
        }
            

        } else {
            //System.out.print(strStageTwoConverted + "-");
            
            intFinal = rand.nextInt(99999 - 1) + 1;
            strStageThreeConverted = String.format("%05d", intFinal);
            //System.out.println(strStageThreeConverted);
            
            if (intDay < 100) {

            strDayConverted = String.format("%03d", intDay);
            lblCode.setText(strDayConverted + String.valueOf(intYear).substring(2) + "-OEM-" + strStageTwoConverted + "-" + strStageThreeConverted);
        } else {
            lblCode.setText(intDay + String.valueOf(intYear).substring(2) + "-OEM-" + strStageTwoConverted + "-" + strStageThreeConverted);
        }

        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelPic;
    private static javax.swing.JTextField lblCode;
    // End of variables declaration//GEN-END:variables
}